### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by SukkaW** [SukkaW/Koolshare-Clash#1]
- [x] KoolClash 检查更新功能
- [x] KoolClash 内置的 clash-dashboard 的更新功能
- [x] 支持 Clash 托管配置
- [x] 让 Clash 外部控制器监听路由器 IP（以便在当前网段内可达）
- [x] Clash 启动停止时的倒计时
- [x] 用 yq 重写配置文件操作逻辑
- [x] 改善关于后备 DNS 配置的文案，提供更详细的说明
- [x] 检测到当前配置文件有 DNS 配置时锁定后备 DNS 输入框和提交按钮、并提供提示
- [x] 改变后备 DNS 逻辑、支持用后备 DNS 覆盖配置文件中的 DNS 设置
- [x] 支持自定义外部控制 IP、端口和密钥
- [x] 操作日志显示
- [x] ~~Clash Dashboard 版本追踪~~
> 不再支持 Clash Dashboard 的更新，Clash Dashboard 跟随 Clash 更新。

- [x] MaxMind 版本号显示
> ~~不再支持 MaxMind IP 库的更新， MaxMind IP 库跟随 Clash 更新。~~ 支持手动更新 IP 库并显示版本号

- [x] 更好的进程管理
- [x] Chromecast DNS 劫持功能
- [x] 将 Clash 作为 dnsmasq 的上游
- [ ] KoolSS 一样的访问控制
  - [x] 全局端口监听控制（常用 HTTP Port 和 指定端口）
  - [ ] 指定主机操作（局域网内设备的放行、通过）
- [x] ipset 白名单 Web 界面
- [ ] 注释默认 dnsmasq 的部分配置以确保能够正常使用

**Comment by taresky** [comment]
KoolSS 一样的访问控制 —— 指定主机操作（局域网内设备的放行、通过）

就等这个了，感谢开发者。
